NMS-12925: Add ToS aggregation
OpenNMS/nephron pull request #12
Opened 2021-01-11 15:44 UTC by swachter

A `tos` aggregation is introduced that is the parent aggregation for applications, conversation, and hosts. In summary, the aggregations now are:

* `exporter/interface`
* `exporter/interface/tos`
* `exporter/interface/tos/application`
* `exporter/interface/tos/conversation`
* `exporter/interface/tos/host`

The `tos` aggregation adds two key parts: one key part for distinguishing `DSCP`s and another key part for distinguishing `ECN`s. Accordingly a `dscp` field and a `ecn` field is added to flow summaries of that aggregation and the subaggregations for applications, conversation, and hosts.

Aggregations are now defined by the `CompoundKeyType` class that specifies which key parts (i.e. exporter, interface, dscp, ecn, application, ...) are used in an aggregation. In future additional aggregations may be defined for optimizing queries. In particular aggregations for `exporter/interface/dscp` and `exporter/interface/ecn` may be useful (cf. [NMS-13086](https://issues.opennms.org/browse/NMS-13086). These aggregations can be implemented easily by defining corresponding compound key type instances using the existing dscp and ecn key part functionality.

If filtering/grouping ECN values is not required and some storage/cpu cost should be saved then the ECN part of ToS could be deactivated in future.

2021-01-19 20:07 UTC, fooker requested changes
Any reason, why the branch name does not follow the typical pattern of `jira/NMS-00000`? By doing so, finding the right branch for others is way more easy.

2021-01-19 20:07 UTC, fooker commented on main/src/test/java/org/opennms/nephron/FlowAnalyzerTest.java
> +        }}).toArray(l -> new FlowSummary[l]);
```suggestion
        List<FlowSummary> summaries = Stream.of(
                        new Expected(EXPORTER_INTERFACE, 0, "SomeFs:SomeFid-98", AggregationType.TOTAL, 28, true, null, null, null, null, null),
                        new Expected(EXPORTER_INTERFACE_APPLICATION, 1, "SomeFs:SomeFid-98-SomeApplication", AggregationType.TOPK, 28, true, null, null, "SomeApplication", null, null),
                        new Expected(EXPORTER_INTERFACE_CONVERSATION, 1, "SomeFs:SomeFid-98-" + conversationKey, AggregationType.TOPK, 28, true, null, null, null, null, conversationKey),
                        new Expected(EXPORTER_INTERFACE_HOST, 1, "SomeFs:SomeFid-98-10.0.0.1", AggregationType.TOPK, 28, true, null, null, null, "10.0.0.1", null),
                        new Expected(EXPORTER_INTERFACE_HOST, 2, "SomeFs:SomeFid-98-10.0.0.2", AggregationType.TOPK, 28, true, null, null, null, "10.0.0.2", null),
                        new Expected(EXPORTER_INTERFACE_TOS, 0, "SomeFs:SomeFid-98-0-ECT", AggregationType.TOTAL, 11, false, 0, 1, null, null, null),
                        new Expected(EXPORTER_INTERFACE_TOS, 0, "SomeFs:SomeFid-98-0-CE", AggregationType.TOTAL, 17, true, 0, 3, null, null, null),
                        new Expected(EXPORTER_INTERFACE_TOS_APPLICATION, 1, "SomeFs:SomeFid-98-0-ECT-SomeApplication", AggregationType.TOPK, 11, false, 0, 1, "SomeApplication", null, null),
                        new Expected(EXPORTER_INTERFACE_TOS_APPLICATION, 1, "SomeFs:SomeFid-98-0-CE-SomeApplication", AggregationType.TOPK, 17, true, 0, 3, "SomeApplication", null, null),
                        new Expected(EXPORTER_INTERFACE_TOS_CONVERSATION, 1, "SomeFs:SomeFid-98-0-ECT-" + conversationKey, AggregationType.TOPK, 11, false, 0, 1, null, null, conversationKey),
                        new Expected(EXPORTER_INTERFACE_TOS_CONVERSATION, 1, "SomeFs:SomeFid-98-0-CE-" + conversationKey, AggregationType.TOPK, 17, true, 0, 3, null, null, conversationKey),
                        new Expected(EXPORTER_INTERFACE_TOS_HOST, 1, "SomeFs:SomeFid-98-0-ECT-10.0.0.1", AggregationType.TOPK, 11, false, 0, 1, null, "10.0.0.1", null),
                        new Expected(EXPORTER_INTERFACE_TOS_HOST, 2, "SomeFs:SomeFid-98-0-ECT-10.0.0.2", AggregationType.TOPK, 11, false, 0, 1, null, "10.0.0.2", null),
                        new Expected(EXPORTER_INTERFACE_TOS_HOST, 1, "SomeFs:SomeFid-98-0-CE-10.0.0.1", AggregationType.TOPK, 17, true, 0, 3, null, "10.0.0.1", null),
                        new Expected(EXPORTER_INTERFACE_TOS_HOST, 2, "SomeFs:SomeFid-98-0-CE-10.0.0.2", AggregationType.TOPK, 17, true, 0, 3, null, "10.0.0.2", null),
        ).map(e -> new FlowSummary() {{
            this.setGroupedByKey(e.groupedByKey);
            this.setTimestamp(1500000060000L);
            this.setRangeStartMs(1500000000000L);
            this.setRangeEndMs(1500000060000L);
            this.setRanking(e.ranking);
            this.setGroupedBy(e.groupedBy);
            this.setAggregationType(e.aggregationType);
            this.setBytesIngress((long)e.bytes);
            this.setBytesEgress(0L);
            this.setBytesTotal((long)e.bytes);
            this.setCongestionEncountered(e.congestionEncountered);
            this.setNonEcnCapableTransport(false);
            this.setIfIndex(98);
            this.setExporter(exporterNode);
            this.setDscp(e.dscp);
            this.setEcn(e.ecn);
            this.setApplication(e.application);
            this.setHostAddress(e.hostAddress);
            this.setConversationKey(e.conversationKey);
        }}).collect(Collectors.toList());
```

Not really relevant in a test, but allocation arrays should be seen as the last-possible option as it involves multiple allocations if size is not know.

2021-01-19 22:07 UTC, Naicisum commented on main/src/main/java/org/opennms/nephron/NephronOptions.java
> +    void setKeyByEcn(boolean value);
@fooker The ECN information can be useful but does not need to be keyed or grouped by Nephron. 

For conversations, It should be treated as MAX(VALUE(ecn)) per Window.

For application pipelines, you would need to count the number of Non-ECT/ECT/CE flags per window, and if you want to do the math up front, then average them over the total seen in a window to get a percentage of each and store just the percentages per window. Else store the counts of each type in the record and calculate percentages downstream.

The Nephron Window is controlled by the user in Nephron so it makes the most sense going this route. This would allow users to be able to see this data per window.

As for a couple of Use Cases:

Grafana/Helm could have a simple filter on these values to simply data display. Regarding conversations, A ECN dropdown that matches the predefined values for a ES query and then showing that data rendered per window with the default being "any" value until specified. If you change it to CE then all the data is filtered which under ideal conditions results in no data (or no congestion for the time period queried). A value of ECT would show you connections that have negotiated ECT, and lastly Non-ECT for conversations that didn't negotiate ECT.

Regarding Applications, this could still be useful to show a percentage of a particular "app" that is Non-ECT/ECT/CE. This might be more useful in the table data of the app. Possibly even a app graph that adds up to 100% and shows the data over time per app on a deep dive view.

2021-01-19 22:14 UTC, Naicisum commented on main/src/main/java/org/opennms/nephron/NephronOptions.java
> +    void setKeyByEcn(boolean value);
@fooker Regarding the application pipeline, the more I think about this, you would also need to ensure the count for app is distinct by conversation to prevent duplicates which skew the count. This may add too much complexity to the pipeline unless you could think of a simple way.

2021-01-20 08:47 UTC, swachter commented
> Any reason, why the branch name does not follow the typical pattern of `jira/NMS-00000`? By doing so, finding the right branch for others is way more easy.

Really? If you type "nms-" GIT offers you all matching branches. I find it more difficult to remember the "nms" code of a branch. The codes should match tickets but maybe there are several tickets for a single branch. If I have my name in the branch name then I know what I am currently working on.

2021-01-20 09:34 UTC, fooker commented on main/src/main/java/org/opennms/nephron/NephronOptions.java
> +    void setKeyByEcn(boolean value);
@Naicisum to clearify: we have two (somewhat distinct) things about ECN in here for now.
First, we store two booleans for each window marking if all flows in that window have negotiated ECN capabilities and if any flow has encountered an congestion.
Second, we group by a tri-state of the ECN flag and create additional windows depending on how the flag is set.

My concerns are sole about the second part. For the first part, I'm open for discussion if it makes sens to store numbers instead of booleans (but we should do this in a separate thread).

2021-01-20 09:46 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Pipeline.java
> +                return -a.getKey().groupedByKey().compareTo(b.getKey().groupedByKey());
I do not see a disadvantage of always having a deterministic ranking.

If tests must carefully crafted to avoid random rankings causing sporadically failing tests then this is a disadvantage.

2021-01-20 10:06 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Aggregate.java
> +    private boolean nonEcnCapableTransport;
`nonEcnCapableTransport` is the established name for ECN = 0. What would `congestionCapable` mean? If we prefer a non-inverted name then `ecnCapableTransport` would be the obvious choice. Unfortunately `ecnCapableTransport` is an established term for ECN = 1 or ECN = 2 and not ECN = 3.

Therefore I decided to stick with the established term and not to invent a new one.

2021-01-20 10:13 UTC, fooker commented on main/src/main/java/org/opennms/nephron/Pipeline.java
> +                return -a.getKey().groupedByKey().compareTo(b.getKey().groupedByKey());
If order doesn't matter, unit tests should not care about order. But leaving unit tests aside, I still don't get why 'b' should come before 'a'.

2021-01-20 10:21 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Pipeline.java
> +                return -a.getKey().groupedByKey().compareTo(b.getKey().groupedByKey());
Some unit tests check for expected flow summary documents. This includes the ranking field that is part of the flow summary documents. If the ranking is random then these checks need additional logic to exclude the ranking field.

"a" is smaller then "b" -> "a" comes before "b"

2021-01-20 10:25 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Ecn.java
> +    IGNORED(-1), // the ECN value is not used for grouping
Null should be avoided!

2021-01-20 10:32 UTC, swachter commented on main/src/main/java/org/opennms/nephron/elastic/FlowSummary.java
> +        }
Equality should be a commutative operation. Using `instanceOf` and considering subtypes makes this complicated.

2021-01-20 10:35 UTC, swachter commented on main/src/main/java/org/opennms/nephron/elastic/FlowSummary.java
> +               Objects.equals(conversationKey, that.conversationKey);
All this code is generated. I trust the IDE. We should really find a solution for the code formatting issue.

2021-01-20 10:56 UTC, fooker commented on main/src/main/java/org/opennms/nephron/Aggregate.java
> +    private boolean nonEcnCapableTransport;
My idea was to use `congestionCapable` (explicitly not choosing `ecnCapableTransport`) for `ECN != 0`.

2021-01-20 11:03 UTC, fooker commented on main/src/main/java/org/opennms/nephron/elastic/FlowSummary.java
> +               Objects.equals(conversationKey, that.conversationKey);
Of course you, as an developer, can trust your IDE to generate the right code. But when it comes to review, there is (for a good reason) no IDE support hiding things. I think making this a general discussion is desirable, but out of scope for this comment.

2021-01-20 11:08 UTC, fooker commented on main/src/main/java/org/opennms/nephron/Ecn.java
> +    IGNORED(-1), // the ECN value is not used for grouping
True. But it is there as a language-construct and will not go away. This means, that that imposing a null-alternative like this one means there are two special cases to handle instead of one if null is used and described explicitly. I think null serves perfectly fine for "this field is empty by intention".

2021-01-20 11:13 UTC, fooker commented on main/src/main/java/org/opennms/nephron/Pipeline.java
> +                return -a.getKey().groupedByKey().compareTo(b.getKey().groupedByKey());
Ok, now I get why this is there: Deserved order is "largest value" followed by "smallest key". As the result of this comparison is inverted to determine the rank, the second order key is inverted (again) to make it appear non-inverted in the output. This is hard to gasp by the comments that are there - they should be revisited.

2021-01-20 11:16 UTC, fooker commented on main/src/main/java/org/opennms/nephron/elastic/FlowSummary.java
> +        }
It doesn't really matter in this case (both versions will work). I just was wondering, if it was changed for a particular reason or if it just is a preference of style or was overwritten by auto-generation.

2021-01-20 11:22 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Groupings.java
> +    }
I added another two lines of comment.

I do not like the host name handling either. It resulted from the previous implementation. I considered various alternatives (e.g. move the host name into the host key part again and exclude it from `equals` and `hashCode` or combining the key creation with the aggregation value initialization) but no alternative seemed more convincing.

The current implementation makes it explicit that created key parts and created keys may be accompanied by a host name or not. I think this is understandable.

2021-01-20 11:40 UTC, fooker commented on main/src/main/java/org/opennms/nephron/Groupings.java
> +    }
> Maybe the last part can be simplified by assuming that the hostname needs only to be stored if it is set on a trailing element. Even if available, the aggregation for exporter/interface/host/dscp does not need to store the hostname.

But this still needs consideration. There is no benefit in storing the same hostname for all groupings but only for the one where the key ends in something having a hostname.

```java
String hostname = refs.get(refs.size() - 1).hostname;
```
should do it.

2021-01-20 11:42 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Pipeline.java
> +            } else {
The `groupedByKey()` method is expensive. Using `ComparisonChain` would require to always invoke it even if the #bytes comparison is non-zero.

2021-01-20 12:43 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Groupings.java
> +            this.parts = parent == null ? (CompoundKeyTypePart<Ref>[])parts : ArrayUtils.addAll(parent.parts, (CompoundKeyTypePart<Ref>[])parts);
The construction of `CompoundKeyType` instances is safe. For efficiency they store the key type parts of their parent and the key type parts that were added at there definition.

The somewhat problematic case is the `CompoundKey` class. There is a constraint (not expressible in Java's type system) that the `refs` list must correspond to the compound key type parts of its `type`. I added a comment that mentions this. In addition, the number of compound key type parts and the number of refs is now checked during construction. The check could be further improved further by checking the classes of the refs. However, IMHO the benefit of early failure does not justify the additional cost.

2021-01-20 12:46 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Groupings.java
> +    );
I chose this implementation variant because it has less boilerplate. I think it is a matter of taste. If you insist then I can change the implementation.

2021-01-20 12:52 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Aggregate.java
> +    private boolean nonEcnCapableTransport;
I think `congestionCapable` is not understandable by its name alone (i.e. without further explanation). Therefore I would stick with `nonEcnCapableTransport`. I admit that an inverted flag may also require an additional mental hop. In this case however, I think that `nonEcnCapableTransport` can be seen as a term of its own, i.e. not as the inversion of `ecnCapableTransport` (which it isn't in the sense of the established term).

2021-01-20 13:00 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Aggregate.java
> +        this.nonEcnCapableTransport = ecn == 0;
I added a comment and references to Wikipedia

2021-01-20 13:21 UTC, fooker commented on main/src/main/java/org/opennms/nephron/Aggregate.java
> +        this.nonEcnCapableTransport = ecn == 0;
Please refer to the according RFC (https://tools.ietf.org/html/rfc3168) as these are the "official" specs.

2021-01-20 13:24 UTC, fooker commented on main/src/main/java/org/opennms/nephron/Groupings.java
> +    );
My primary problem with this is, that relies on the IDE support to show variable names. Looking at these calls to `keyPart` does absolutely not show which  parameter does what.

2021-01-20 13:28 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Ecn.java
> +    IGNORED(-1), // the ECN value is not used for grouping
I think that null should be avoided in this case. I can add a null check in the constructor of EcnRef that prevents that one must consider an unset ecn value. The `ecn` value is accessed during key encoding. I would have to invent an encoding for the null case.

2021-01-20 13:29 UTC, fooker commented on main/src/main/java/org/opennms/nephron/Pipeline.java
> +            } else {
Good point. Besides that, does it make sense to to build the value during construction and just return it?

2021-01-20 13:35 UTC, fooker commented on main/src/main/java/org/opennms/nephron/Aggregate.java
> +    private boolean nonEcnCapableTransport;
> not as the inversion of `ecnCapableTransport` (which it isn't in the sense of the established term).

This sentence alone has to many inversions. I cant see the logic behind storing that a feature is *not* available. But I think this will work, too.

2021-01-20 13:47 UTC, fooker commented on main/src/main/java/org/opennms/nephron/Ecn.java
> +    IGNORED(-1), // the ECN value is not used for grouping
There is a `NullableCoder` in the beam SDK for exact this use-case.

2021-01-20 13:55 UTC, fooker commented on main/src/main/java/org/opennms/nephron/Groupings.java
> +            this.parts = parent == null ? (CompoundKeyTypePart<Ref>[])parts : ArrayUtils.addAll(parent.parts, (CompoundKeyTypePart<Ref>[])parts);
I'm aware that the build a concatenated list of their parents parts and their own. By "unsafety", I mean that casting from `CompoundKeyTypePart<? extends Ref>` to `CompoundKeyTypePart<Ref>` can be problematic as it would allow to to call any method of i.e. an instance of `CompoundKeyTypePart<MyRefImpl>` which is bound to the type parameter with an arbitrary Implementation of `Ref` which mus not necessarily match the expected type.

The better way to express this with the java type system is ... the visitor pattern.

2021-01-20 14:01 UTC, swachter commented on main/src/main/java/org/opennms/nephron/NephronOptions.java
> +    void setKeyByEcn(boolean value);
> I'm still **strongly** opting for not doing this. using the ECN flags for keying has multiple drawbacks:
> 
>     * The accumulated values are higher than they are for real: The flag is set by the router exporting a flow if _any_ packet of the flow has the flag set. Meaning that we report the packets of the whole flow as suffering from congestion. For example: consider two flows with the same amount of bytes/packets transmitted but only one packet had ever set the 'congestion encountered' flag. This would lead to report that 50% of the packets are impacted by congestion.
 

The information must be seen as what it is.

>     * The code complexity for this is non-trivial, as it involves not only the grouping in nephron itself, but also the querying from OpenNMS, the filtering and the graphing.

The increased code complexity for having ecn grouping in Nephron is minimal. There is no special casing for this grouping. It works like every other grouping dimension.

The only additional complexity is the switch to turn on ECN grouping. This feature is implemented by a few lines.

> The current implementation allows to short-cut the query to the parent grouping (query for all DSCP in application is equal to query for application, etc) but not for ECN as DSCP and ECN are on the same level in the compound key. This prohibits to query for ECN values qithout querying for DSCP values. too.

I do not understand the limitations you mention here. All variants of exisiting/non-exisiting DSCP/ECN filters can be processed. It was decided that the ToS aggregations should be exhaustive. Therefore no total parent aggregations must exist for calculating "other" contributions.


> In addition, the raw data implementation in OpenNMS must support a similar behavior. If the code is released once, we have to support it - and somebody will turn on this flag and start to ask questions about it.

The `dscp` and `ecn` fields exist in raw flows. When ecn grouping is activated then the `ecn` field gets calculated for the ToS aggregations and its subaggregations. This aligns flow summaries and raw flows in this regard.

> 
>     * Even if the calculation would be correct, this is not an information that is interesting. In almost all cases, there is nothing an admin can do about congestion as this is only signaling for a problem happening somewhere on the whole path (or maybe even on the other direction on the path - due to asymmetric routing not even passing through the monitored device). Seeing this flag does not mean, that the router monitored is creating the congestion.

Again, the information must be seen as what it is.

> 
>     * If enabled, the increase in storage-usage would explode from 64 for DSCP only to 192.

The DSCP part should not be considered when discussing the ECN part. Switching ECN grouping on may increase storage cost by a factor of 3 for the ToS aggregations and its subaggregations. The actual factor depends on the distribution of ecn bits. (The addional aggregations without ToS are not affected at all).


> 
>     * Analyzing congestion is only relevant for specific conversations. Keying the data does no provide this information whereas the flag in the `FlowSummary` does.

Grouping the data by ecn allows to filter for flows that have certain ECN values (for example had a congestion for sure). Such flows may not have made it into the topK at some node because of their congestion.

> 
> 
> I've tried to address this multiple times before. Therefore I'd like to bring this to a wider discussion.
> 
> @Naicisum can you comment on how this may be useful in your environment?
> 
> @j-white CC

2021-01-20 14:16 UTC, swachter commented on main/src/main/java/org/opennms/nephron/NephronOptions.java
> +    void setKeyByEcn(boolean value);
> @fooker The ECN information can be useful but does not need to be keyed or grouped by Nephron.
> 
> For conversations, It should be treated as MAX(VALUE(ecn)) per Window.
> 
> For application pipelines, you would need to count the number of Non-ECT/ECT/CE flags per window, and if you want to do the math up front, then average them over the total seen in a window to get a percentage of each and store just the percentages per window. Else store the counts of each type in the record and calculate percentages downstream.

At the moment the minimum and the maximum are calculated, i.e. there is a boolean flag that indicates if there was a flow with ECN=0 in that was part of a window and another flag that indicates if there was a flow with ECN=3. A histogram for the ECN values could be aggregated easily.


> As for a couple of Use Cases:
> 
> Grafana/Helm could have a simple filter on these values to simply data display. Regarding conversations, A ECN dropdown that matches the predefined values for a ES query and then showing that data rendered per window with the default being "any" value until specified. If you change it to CE then all the data is filtered which under ideal conditions results in no data (or no congestion for the time period queried). A value of ECT would show you connections that have negotiated ECT, and lastly Non-ECT for conversations that didn't negotiate ECT.

The straight-forward solution to this is to switch on the ECN grouping. In that case there are aggregations that have an ecn field that can be used for filtering.

> 
> Regarding Applications, this could still be useful to show a percentage of a particular "app" that is Non-ECT/ECT/CE. This might be more useful in the table data of the app. Possibly even a app graph that adds up to 100% and shows the data over time per app on a deep dive view.

The above mentioned histogram for ECN values may cover this. For each app we could display the percentages for the three classes of ECNs.

2021-01-20 16:05 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Ecn.java
> +    IGNORED(-1), // the ECN value is not used for grouping
I see no benefit in using `null` here. I understand if null is used for performance reasons. In case of the `NullableCoder` an additional byte is used to distinguish null values. I still think that the explicit `IGNORED` value is more informative than a missing value. After all it might be missing for various reasons (including programing errors).

More generally, there are a lot of indications that `null` should be avoided in general. I would reverse the decision logic: You must have very good reasons to justify the use of `null`.

2021-01-20 17:05 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Groupings.java
> +            this.parts = parent == null ? (CompoundKeyTypePart<Ref>[])parts : ArrayUtils.addAll(parent.parts, (CompoundKeyTypePart<Ref>[])parts);
The problematic method is the encode method:

```
        void encode(List<Ref> refs, OutputStream os) throws IOException {
            for (int i = 0; i < parts.length; i++) {
                parts[i].encode(refs.get(i), os);
            }
        }

```

`parts[i].encode(refs.get(i), os);` can not be called if the type parameter of `parts[i]` is a wildcard type parameter (because the type parameter appears in contravariant position on that call). However, that call is guaranteed to succeed if the parts and refs correspond which is (should) be guaranteed by construction of `CompoundKey` instances.

There is another location that suffers from the same situation, namely the `CompoundKey.populate()` method:

```
        public void populate(FlowSummary flow) {
            flow.setGroupedBy(type);
            flow.setGroupedByKey(groupedByKey());
            for (int i = 0; i < type.parts.length; i++) {
                type.parts[i].populate(refs.get(i), flow);
            }
        }
```

`type.parts[i].populate(refs.get(i), flow);` can not be called if the type parameter of `type.parts[i]` is a wildcard type. Again, this call is guaranteed to succeed.

I could change the type of `CompoundKeyType.parts` from `private CompoundKeyTypePart<Ref>[] parts;` into `private CompoundKeyTypePart<?>[] parts;`. Then the cast in the constructor would no more be necessary but casts at the two mentioned location would be required. Comments on these two casts would justify them as being safe.

I do not see how the visitor pattern could improve the situation here. There is a list of parts that have different and unknown type parameters and matching list of subtypes of refs that match these type parameters. The visitor pattern could be used to implement a double dispatch (based on part and ref) but when a part of a certain type would be visited by non-matching subtype of a ref then there would need to be an exception too.

2021-01-20 17:19 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Groupings.java
> +    }
Will do. Can you explain why the host name should be set only if its contained in the last part?

2021-01-20 17:32 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Groupings.java
> + * of key parts are represented by implementations of the {@link Ref} interface.
Conceptually, `CompoundKey`s were a list of key parts before the change. The implementation had some code duplication and would not allow to easily compose different kinds of aggregations.

2021-01-20 17:50 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Groupings.java
> +            }
I did not look into the code that exports flows to Kafka. Is the `flowdocument.proto` contained in `nephron/proto` used there? If that is the case we could enrich the Kafka-Export to contain tos-splitting logic and add additional fields for dscp and ecn. Should the tos field be kept in that case? I am not sure, if that would worth it.

Another issue is, that in Nephron the cases ECN=1 and ECN=2 are treated the same. It is questionable where this piece of logic should be located. It can be argued that it should apply both, to raw flows and flow summaries. OTOH it might be preferable to have raw flows unmodified.

In summary, I think we could move the tos-splitting logic into OpenNMS but the further classification what to consider and what not should be kept in nephron.

2021-01-20 18:35 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Pipeline.java
> +            } else {
I think that the second comparison criteria is not evaluated often in practice. It will happen only if the total number of bytes are the same for two entries to be ranked. Therefore I would not precalculate the value for this usage only.

ATM the `groupedByKey` is used when populating the exported flow summaries. However, this happens for exported result collections only. Keys that may be used in intermediary groups may not be transformed into the string representation at all.

In summary, I would not precalculate / cache that property.

2021-01-20 18:40 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Pipeline.java
> +                return -a.getKey().groupedByKey().compareTo(b.getKey().groupedByKey());
updated comment and implementation

2021-01-20 19:24 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Groupings.java
> +    );
I can move a  `CompoundKeyTypePart`, `CompoundKeyType`, `CompoundKey`, and `Ref` into files of their own. In that case I would propose to rename `CompoundKeyTypePart` into `RefType`. This make the relation to the `Ref` hierarchy more explicit.

2021-01-20 19:34 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Aggregate.java
> +        this.nonEcnCapableTransport = ecn == 0;
done

2021-01-20 20:22 UTC, Naicisum commented on main/src/main/java/org/opennms/nephron/NephronOptions.java
> +    void setKeyByEcn(boolean value);
> At the moment the minimum and the maximum are calculated, i.e. there is a boolean flag that indicates if there was a flow with ECN=0 that was part of a window and another flag that indicates if there was a flow with ECN=3. A histogram for the ECN values could be aggregated easily.

Minimum is never needed in a single conversation, only maximum. There is no use case where I need to know a minimum. Since the parameter is created from Off/On/Issue, by default if there is a Issue, then I also know its On. If its On, then I know it's not Off.

Could you explain your reasoning for needing to know a minimum per window?

-----
> The straight-forward solution to this is to switch on the ECN grouping. In that case there are aggregations that have an ecn field that can be used for filtering.

This is not aggregation, this is filtering, and should be handled by a ES query via OpenNMS Rest API.


-----
> > Regarding Applications, this could still be useful to show a percentage of a particular "app" that is Non-ECT/ECT/CE. This might be more useful in the table data of the app. Possibly even a app graph that adds up to 100% and shows the data over time per app on a deep dive view.
> 
> The above mentioned histogram for ECN values may cover this. For each app we could display the percentages for the three classes of ECNs.

I'm not really sold so much on the app percentage over time, the ECN metric is much more useful in a per conversation view. So I can go either way on having it or not.

-----
@fooker @swachter  The most important part of all of this is to not increase complexity so much that computational load becomes untenable.

2021-01-21 07:46 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Groupings.java
> +            this.parts = parent == null ? (CompoundKeyTypePart<Ref>[])parts : ArrayUtils.addAll(parent.parts, (CompoundKeyTypePart<Ref>[])parts);
After some more thought: There is a possibility to remove the casts. The `CompoundKeyTypePart.encode(ref, os)` and `CompoundKeyTypePart.populate(ref, flow)` methods can be moved to the `Ref` interface. The downside of this change is though, that then serialization logic is implemented in `Ref` instances whereas the deserialization logic stays in `CompoundKeyTypePart` instances.

In my opinion there are three options (assuming that the structure of the `CompoundKeyType` is not changed):
1. Use `CompoundKeyTypePart<Ref>[] parts` member with a cast in the constructor (current implementation)
2. Use `CompoundKeyTypePart<?>[] parts` member with casts in `encode` and `populate` (discussed above)
3. Move `encode` and `populate` logic into `Ref` hierarchy. No casts necessary but serder logic is split

2021-01-21 09:35 UTC, swachter commented on main/src/main/java/org/opennms/nephron/NephronOptions.java
> +    void setKeyByEcn(boolean value);
> > At the moment the minimum and the maximum are calculated, i.e. there is a boolean flag that indicates if there was a flow with ECN=0 that was part of a window and another flag that indicates if there was a flow with ECN=3. A histogram for the ECN values could be aggregated easily.
> 
> Minimum is never needed in a single conversation, only maximum. There is no use case where I need to know a minimum. Since the parameter is created from Off/On/Issue, by default if there is a Issue, then I also know its On. If its On, then I know it's not Off.
> 
> Could you explain your reasoning for needing to know a minimum per window?
> 

I thought that the information that there was some `nonEcnCapableTransport` in a selected time range is useful.

(BTW: The minimum and maximum values are calculated per window and are aggregated by elastic over the selected time range. The start or end of a conversations is not considered. In my opinion conversations could be handled more specifically by using the concept of session windows. This would surely require additional thinking, though.)

The decision to calculate the minimum and maximum value was also inspired by "mathematical" thinking: How could a set of ECN values be summarized.

After more thinking, instead of the histogram mentioned in my last comment we could also split the traffic volume information (total/ingress/egress) into 3 parts, namely volume with ECN=0, volume with ECN=1|2, and volume with ECN=3. I think this requires some work on the Drift plugin, though.

> > The straight-forward solution to this is to switch on the ECN grouping. In that case there are aggregations that have an ecn field that can be used for filtering.
> 
> This is not aggregation, this is filtering, and should be handled by a ES query via OpenNMS Rest API.
> 

We can filter for ECN values only if they were used for aggregations. In other words, only the exporter/interface/tos aggregation and its subaggregations for exporter/interface/tos/(app|host|conv) have an ecn field (assuming groupByEcn is enabled).

Any ecn related summary information that may be calculated during aggregations could also be used for filtering. However, you have to keep in mind that the `topK` pruning of (app|host|conv)-aggregations is based on volume. Low volume (apps|hosts|convs) may not show up if they suffered from a lot `congestionEncountered` (ECN=3).


> > > Regarding Applications, this could still be useful to show a percentage of a particular "app" that is Non-ECT/ECT/CE. This might be more useful in the table data of the app. Possibly even a app graph that adds up to 100% and shows the data over time per app on a deep dive view.
> > 
> > 
> > The above mentioned histogram for ECN values may cover this. For each app we could display the percentages for the three classes of ECNs.
> 
> I'm not really sold so much on the app percentage over time, the ECN metric is much more useful in a per conversation view. So I can go either way on having it or not.

If the splitted volume information is calculated (see above) then the application summary table can show percentages for the 3 ECN classes. (Only results for topK apps would be available, though).

I had no "app percentages over time" in mind. Percentages would be available in the summary table only. The drift plugin would need to be extended again to cover series.

> 
> @fooker @swachter The most important part of all of this is to not increase complexity so much that computational load becomes untenable.

There will certainly be more flow summary documents that have to be persisted. If Elastic write is a concern then using different indexes for different aggregations may help here.

I am not so sure about the influence on the computational load. ATM raw input is processed 4 times (one time for the exporter/interface aggregation and three times for the exporter/interface/(app, host, conv) aggregations. With this pull request raw input is processed 8 times because of the additional aggregations. This can be reduced to 3 times if aggregations are build on each other. (For example the aggregation exporter/interface can be computed from the aggregation exporter/interface/app). I am working on another pull for this change. This change may have a bigger impact regarding the handling of late data, though.

2021-01-21 09:48 UTC, fooker commented on main/src/main/java/org/opennms/nephron/Groupings.java
> +    );
Make it so.

2021-01-26 10:08 UTC, fooker commented on main/src/main/java/org/opennms/nephron/Groupings.java
> +    }
Querying for hostnames is always done by a separate query which just filters by IP and time range. As the hostnames are piggybacked with the aggregations and queried independently there is no need to store the duplicated information of IP -> Hostname.

2021-01-26 10:14 UTC, fooker commented on main/src/main/java/org/opennms/nephron/Groupings.java
> +            }
`flowdocument.proto` is the right spot. It is also defined in OpenNMS code. The flow documents generated there already have the additional fields for DSCP and ECN and they just needed to be added to the transport representation.

I think adding it to https://github.com/OpenNMS/opennms/blob/874467a957bcd4cd283943ac4070c63439a25a74/features/flows/api/src/main/java/org/opennms/netmgt/flows/api/Flow.java would be the right place.

2021-01-26 10:29 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Groupings.java
> +    }
Makes sense. Added corresponding comment.

2021-01-26 10:44 UTC, fooker commented on main/src/main/java/org/opennms/nephron/Pipeline.java
> +            } else {
Ok.

2021-01-26 10:54 UTC, fooker commented on main/src/main/java/org/opennms/nephron/NephronOptions.java
> +    void setKeyByEcn(boolean value);
Some more thoughts about the complexity (code-wise and conceptionaly) this adds:
* It increases the code complexity of the grouping keys from being a simple list to a tree, because DSCP and ECN are orthogonal dimensions. This includes the whole type-safety discussion below.
* All queries for the aggregated data must handle both cases as the data is either set or ignored
* Providing the filter in the UI but having the flag disabled will result no results shown - which is super hard to explain

2021-01-26 10:57 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Groupings.java
> +            }
I can add `dscp` and `ecn` fields to the two copies of `flowdocment.proto`. However, I would still prefer to use the already existing `tos` field for now. This allows to update Nephron without updating OpenNMS.

2021-01-26 10:58 UTC, fooker commented on main/src/main/java/org/opennms/nephron/Groupings.java
> +            }
Whats the use-case for updating one without the other? There is no way to query the data...

2021-01-26 10:59 UTC, fooker commented on main/src/main/java/org/opennms/nephron/Groupings.java
> +            }
I don't like the fact that this clutters and duplicates protocol specific implementation details all over the place.

2021-01-26 11:36 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Groupings.java
> +            }
The data can be queried using Kibana. I think being able to deploy Nephron independently of OpenNMS may ease installation.

I do not understand your argument. Can you please detail "what protocol specific implementation details" you have in mind.

AFAIS the current Nephron implementation contains two pieces of duplicated logic that already exist in OpenNMS:

1. Calculate the DSCP value from a ToS value: `tos >>> 2`
2. Calculate the ECN value from a ToS value: `tos & 3`

I think it is justifiable to have these pieces of logic duplicated. However, you proposed not to duplicate that logic, but to add DSCP and ECN fields to the protocol buffer (in addition to the already existing TOS field).

2021-01-26 11:41 UTC, fooker commented on main/src/main/java/org/opennms/nephron/Groupings.java
> +            }
By protocol specific, I mean the details and knowledge required to parse parts out of the IP header. Even if the parsing is simple, the concept behind parsing all these fields should be kept separately.

I think it's justifiable to just add the fields and copy over the already parsed values.

Protobuf ensures backward-compatibility allowing to upgrade nephron without upgrading opennms.

2021-01-26 11:55 UTC, swachter commented on main/src/main/java/org/opennms/nephron/NephronOptions.java
> +    void setKeyByEcn(boolean value);
> Some more thoughts about the complexity (code-wise and conceptionaly) this adds:
> 
>     * It increases the code complexity of the grouping keys from being a simple list to a tree, because DSCP and ECN are orthogonal dimensions.

The aggregation or key structure is not changed. In database terminology you can view DSCP/ECN as a compound key (part).

> This includes the whole type-safety discussion below.

The type-safety discussion below has nothing to do with the DSCP/ECN issue. Type-safety aspects have changed because the former `CompoundKey` class hierarchy that contained subclasses for all kinds of possible keys was replaced by a single implementation that contains a list of key parts. The new implementation is type safe. The cast(s) can either be proven that they can not fail or the serder logic can be refactored.

> 
>     * All queries for the aggregated data must handle both cases as the data is either set or ignored

DSCP/ECN are no different than all other filters. If a parameter for a filter exists it is applied and otherwise not.

> 
>     * Providing the filter in the UI but having the flag disabled will result no results shown - which is super hard to explain

The values for the ECN filter are fetched from Elastic. If ECN grouping is disabled then no ECN value can be selected. This effectively disables the ECN filter.

2021-01-26 12:25 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Groupings.java
> +            }
Should the case that DSCP/ECN is not set in protobuf messages be considered? Should there be a fallback to the TOS field or straight to some "default" DSCP/ECN values?

AFAIS the `flowdocument.proto` messages are created based on data from `org.opennms.netmgt.flows.api.EnrichedFlow/Flow` instances [FlowDocumentBuilder](https://github.com/OpenNMS/opennms/blob/develop/features/flows/kafka-persistence/src/main/java/org/opennms/netmgt/flows/persistence/FlowDocumentBuilder.java)

 `EnrichedFlow/Flow` contain no DSCP/ECN information/logic. DSCP/ECN logic is part of the `org.opennms.netmgt.flows.elastic.FlowDocument`. DSCP/ECN logic can be added to `Flow` and can be used for Kafka protobuf messages. Is this what you have in mind?

2021-01-26 12:41 UTC, fooker commented on main/src/main/java/org/opennms/nephron/Groupings.java
> +            }
> Should the case that DSCP/ECN is not set in protobuf messages be considered? Should there be a fallback to the TOS field or straight to some "default" DSCP/ECN values?

Would just set it to ~`null`~ `Ecn.IGNORED`?

> `EnrichedFlow/Flow` contain no DSCP/ECN information/logic. DSCP/ECN logic is part of the `org.opennms.netmgt.flows.elastic.FlowDocument`. DSCP/ECN logic can be added to `Flow` and can be used for Kafka protobuf messages. Is this what you have in mind?

Yup.

2021-01-27 09:05 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Groupings.java
> +            }
add dscp/ecn fields to protobuf; removed tos -> dscp/ecn logic from nephron

2021-01-28 14:47 UTC, mszoek commented on main/src/main/java/org/opennms/nephron/NephronOptions.java
> +    void setKeyByEcn(boolean value);
Hi guys... I have been thinking about this thread. There are good points both ways. However, I think supporting ECN at this time is not necessary, creates some additional complexity/work items, and also adds risk that we will push the compute resources over the limit. Let's remove the ECN parts and focus on DSCP for now to get this merged. We can follow up with ECN support (if needed) once we see how this performs.

2021-01-28 15:44 UTC, swachter commented on main/src/main/java/org/opennms/nephron/NephronOptions.java
> +    void setKeyByEcn(boolean value);
Ok. I will remove the ECN grouping related stuff from this PR and the PRs for OpenNMS, OpenNMS-JS, and OpenNMS-Helm.

2021-02-02 10:49 UTC, fooker approved these changes
This looks very good code-wise.

Before merging I would like to give the whole stack a test-run.

2021-02-02 10:51 UTC, fooker commented
@Naicisum I think this is in a state where we can do some production tests. This is backward and forward compatible. It would only create additional aggregations, currently ignored by OpenNMS.

2021-02-08 20:11 UTC, fooker commented
@swachter I think we have to revisit the `nonEcnCapableTransport` discussion again. While testing, I found that there is quite a difference between storing the inverted version as we do now or storing if a flow was congestion-aware. As these values are aggregated, there is currently no way to figure out if only some of the flows in a bucket are congestion-aware. The `nonEcnCapableTransport` will only be set to false, if **all** flows in a bucket are congestion-aware. I'm not certain if this is the information we want. Maybe it is more feasible to use counters instead of booleans.

2021-02-09 08:08 UTC, swachter commented
Counters for the different ECN classes can be added easily to Nephron. I assume that the drift plugin could sum up these counters over windows the same way it sums up the numbers of bytes. For performance reasons the drift plugin should do these summations in one go, though. (I already have in mind to calculate ingress/egress in one go).

I wonder if the volume per ECN class would also be of interest.

However, can we postpone further ECN related modifications? I had the impression that ECN was not in the focus of this work. If more detailed insight into ECN related information is required then maybe an ECN grouping would still be an option.

2021-04-21 13:15 UTC, merged