Swachter/flow sampling
OpenNMS/nephron pull request #14
Opened 2021-02-01 08:24 UTC by swachter

This PR fixes rounding errors that might happen when flows are sampled into their windows.

* moves the check for a negative flow duration into the windows assignment function
* changes the sampling logic that calculates the number of bytes that flows contribute to windows
* adds a property based test that checks that the sum of sampled contributions is equal to the number of bytes of a flow

2021-02-01 14:24 UTC, Naicisum requested changes

2021-02-01 14:24 UTC, Naicisum commented on main/src/main/java/org/opennms/nephron/FlowWindows.java
> +        long lastWindow = lastSwitchedMillis / windowSize;
This condition is handled by Minion now. Dropping flows are not an option.

2021-02-01 14:58 UTC, swachter commented on main/src/main/java/org/opennms/nephron/FlowWindows.java
> +        long lastWindow = lastSwitchedMillis / windowSize;
Flows are already dropped in the current implementation (cf. https://github.com/OpenNMS/nephron/blob/master/main/src/main/java/org/opennms/nephron/Groupings.java#L144) when corresponding aggregates are calculates.

The change introduced here is that the flows would already be dropped when they are distributed to their windows.

2021-02-01 15:10 UTC, Naicisum commented on main/src/main/java/org/opennms/nephron/FlowWindows.java
> +        long lastWindow = lastSwitchedMillis / windowSize;
Then that section needs to be removed as well. Any unnecessary cpu time needs to be eliminated.

2021-02-01 17:15 UTC, swachter commented on main/src/main/java/org/opennms/nephron/FlowWindows.java
> +        long lastWindow = lastSwitchedMillis / windowSize;
I agree, that unnecessary work should be avoided, in general. However, we also have to consider robustness. I am not sure if Minions are the only sources of flows.

@fooker Are Minions the only sources of flows? Can the guard `lastSwitched < deltaSwitched` be dropped or maybe moved into OpenNMS?

2021-02-02 12:47 UTC, fooker requested changes
Just minor nits.
I like the property based testing.

2021-02-02 12:47 UTC, fooker commented on main/src/main/java/org/opennms/nephron/FlowWindows.java
> +        long lastWindow = lastSwitchedMillis / windowSize;
For now, we can assume all flows are processed/created by OpenNMS. If we need save-guards, we can add them there (either, if protocol specific on the parsers running on minions or in general on the adapters running on sentinel).

2021-02-02 12:47 UTC, fooker commented on main/src/main/java/org/opennms/nephron/Groupings.java
> +                    multiplier = samplingInterval;
Can we do the upsampling multiplication outside of the `bytesInWindow` function and just pas in (the already multiplied bytes)? This makes it more clear, that this multiplication has nothing to do with the windowing but is soley protocol related (tbh, I don't even know why we transport this, not doing it on sentinel).

2021-02-02 12:47 UTC, fooker commented on main/src/main/java/org/opennms/nephron/Groupings.java
> +                    multiplier = samplingInterval;
I also don't even know why the sampling interval is transported as a double... There is no such thing as "oversampling".
This is not a fault of your change - but a thing we maybe have to revisit in general.

2021-02-02 13:36 UTC, swachter commented on main/src/main/java/org/opennms/nephron/FlowWindows.java
> +        long lastWindow = lastSwitchedMillis / windowSize;
Dropped the `lastSwitched < deltaSwitched` safe-guard.

2021-02-02 13:42 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Groupings.java
> +                    multiplier = samplingInterval;
done

2021-02-02 13:47 UTC, fooker approved these changes

2021-02-02 15:48 UTC, merged