NMS-13131: Use unaligned windows for different exporters
OpenNMS/nephron pull request #16
Opened 2021-03-10 12:30 UTC by swachter

https://issues.opennms.org/browse/NMS-13131

In addition to using unaligned windows, the execution of unit tests by the surefire plugin is reactivated. (Adding jqwik test had the surprising side effect that standard junit tests were no more detected.)

2021-03-10 13:10 UTC, fooker requested changes

2021-03-10 16:54 UTC, swachter commented on main/src/main/java/org/opennms/nephron/UnalignedFixedWindows.java
> +        return Math.abs(Integer.hashCode(nodeId)) % windowSize;
Good catch! I added a dependency on `fastutil` and use `HashCommon.mix(int)`.

2021-03-11 00:46 UTC, Naicisum approved these changes
Tested, no detected issues. LGTM!

2021-03-11 09:29 UTC, fooker approved these changes

2021-03-11 10:56 UTC, merged