calculate aggregations on-top of each other
OpenNMS/nephron pull request #20
Opened 2021-03-31 08:14 UTC by swachter

https://issues.opennms.org/browse/NMS-13100

2021-04-14 13:25 UTC, fooker requested changes
Maybe the handling of the `CompoundKey` handling regarding "with TOS" and "without TOS" can be further simplified: The order of elements in the key does not really matter, right? If we put TOS last in the key, this would simply result in some kind of `parent()` operation which drops the last element in the compound key. This also applies for the compound key type.

2021-04-14 13:25 UTC, fooker commented on main/src/main/java/org/opennms/nephron/Pipeline.java
> +    }
Can these two classes be unified?

2021-04-14 15:41 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Ref.java
> +     */
Good catch. Can no more be `null`. Was a leftover from the ecn related keying logic. I change that comment and remove the null-ness filter below.

2021-04-14 15:47 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Pipeline.java
> +                   new Aggregate(0, bytes, hostname, flow.hasEcn() ? flow.getEcn().getValue() : null);
Yes. (Caused by not relying on `tos` as it originally did.)

2021-04-14 15:48 UTC, swachter commented on main/src/main/java/org/opennms/nephron/CompoundKey.java
> +        return refs.stream().map(Ref::idAsString).filter(s -> s != null).collect(Collectors.joining("-"));
removed filter

2021-04-14 15:50 UTC, fooker commented on main/src/main/java/org/opennms/nephron/Pipeline.java
> +                   new Aggregate(0, bytes, hostname, flow.hasEcn() ? flow.getEcn().getValue() : null);
C'mon. Give it a separate commit and an appropriate commit message. And maybe link this to NMS-13099 (by doing so in the commit message=

2021-04-14 15:53 UTC, fooker commented
Overall style: The commit message lacks the issue number according to our agreed styles. Same was true for the PR title. And it would be nice to have a sentence or two in the PR description explaining what this change does (in contrast to the issue, which explains the problem, not the solution).

2021-04-14 15:56 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Pipeline.java
> +    }
Yes, they could be unified. However, I think the code is more readable if separate classes are used. I would prefer to leave it as is.

2021-04-14 16:07 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Pipeline.java
> +                   new Aggregate(0, bytes, hostname, flow.hasEcn() ? flow.getEcn().getValue() : null);
I could add a commit to the `nms-12945` branch which does the `.hasEcn()` and rebase this branch again. on `nms-12945`. Estimated time: 1h. Is this what you want?

2021-04-14 16:52 UTC, swachter commented
> Maybe the handling of the `CompoundKey` handling regarding "with TOS" and "without TOS" can be further simplified: The order of elements in the key does not really matter, right? If we put TOS last in the key, this would simply result in some kind of `parent()` operation which drops the last element in the compound key. This also applies for the compound key type.

Alternatively, we could leave the `CompoundKeyType` class unchanged and replace the currently used `CompoundKey.project()` method by a method that just drops the second last key part.

2021-04-20 08:20 UTC, fooker commented on main/src/main/java/org/opennms/nephron/Pipeline.java
> +                   new Aggregate(0, bytes, hostname, flow.hasEcn() ? flow.getEcn().getValue() : null);
Just make it two commits and describe in the commit message what the reason for this is. It should take not more than 10 minutes.

2021-04-20 08:24 UTC, fooker commented
> > Maybe the handling of the `CompoundKey` handling regarding "with TOS" and "without TOS" can be further simplified: The order of elements in the key does not really matter, right? If we put TOS last in the key, this would simply result in some kind of `parent()` operation which drops the last element in the compound key. This also applies for the compound key type.
> 
> Alternatively, we could leave the `CompoundKeyType` class unchanged and replace the currently used `CompoundKey.project()` method by a method that just drops the second last key part.

If you don't like to change the structure of the keys, the current implementation is fine.

2021-04-20 10:11 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Pipeline.java
> +                   new Aggregate(0, bytes, hostname, flow.hasEcn() ? flow.getEcn().getValue() : null);
done

2021-04-21 12:03 UTC, fooker approved these changes

2021-04-21 12:54 UTC, merged