NMS-13262: Update Java and Flink
OpenNMS/nephron pull request #23
Opened 2021-05-17 08:18 UTC by swachter

* Updates Java 8 -> 11
* Updates Flink 1.10 -> 1.12
* Adds a check that timestamps are not too small for the unaligned windows logic

(The timestamp check is only relevant for testing when very small timestamps may be used.)

2021-05-17 15:32 UTC, Naicisum requested changes

2021-05-17 15:32 UTC, Naicisum commented on main/src/main/java/org/opennms/nephron/UnalignedFixedWindows.java
> +        if (timestamp < shift) {
Need to change this logic, this could potentially happen quite often and killing the job would not help analyze the frequency. Better to rate limit log this condition and figure out a fall back behavior.

2021-05-18 12:52 UTC, swachter commented on main/src/main/java/org/opennms/nephron/UnalignedFixedWindows.java
> +        if (timestamp < shift) {
Ok. I moved the timestamp check into the window assignment. Instead of throwing an exception now flows are filtered and logged.

2021-05-18 16:44 UTC, Naicisum approved these changes

2021-05-19 11:19 UTC, fooker approved these changes

2021-05-19 12:53 UTC, merged