NMS-13132: derive aggregations for hosts and applications from the aggregation for conversations
OpenNMS/nephron pull request #24
Opened 2021-05-17 10:40 UTC by swachter

Issue: https://issues.opennms.org/browse/NMS-13132

* Calculates aggregations for hosts/applications on-top of the aggregations for conversations
* The `Aggregation` class now can track two host names (in case of conversation it tracks the src and dst hostname)
* Key creation logic is simplified by decoupling it from src/dst hostname logic. Now, only a single key is returned for a document (previously key creation could return two `WithHostname` instances capturing the src and dst hostnames). Src/dst hostnames are now considered when the keys of conversation aggregations are mapped into two host keys for the two hosts taking part in that conversation.

2021-05-25 14:17 UTC, fooker requested changes

2021-05-25 14:17 UTC, fooker commented on main/src/main/java/org/opennms/nephron/MissingFieldsException.java
> +public class MissingFieldsException extends RuntimeException {
I would like this to stay an explicit exception as it helped to find oddities in the transport protocol a bunch of times.

2021-05-25 15:36 UTC, swachter commented on main/src/main/java/org/opennms/nephron/MissingFieldsException.java
> +public class MissingFieldsException extends RuntimeException {
Ok. Changed back to checked exception.

2021-05-26 08:32 UTC, fooker approved these changes

2021-05-26 12:20 UTC, merged