NMS-13373: add CortexIo
OpenNMS/nephron pull request #31
Opened 2021-07-19 14:36 UTC by swachter

Issues:
* https://issues.opennms.org/browse/NMS-13373
* https://issues.opennms.org/browse/NMS-13403

This PR is marked as a draft PR but the implementation should be production ready. This PR  does not yet include results from the [Cortex investigation task](https://issues.opennms.org/browse/NMS-13375). There is also an open issue that may be tackled in a separate issue, namely garbage collecting some state that may pile up (cf. [NMS-13375](https://issues.opennms.org/browse/NMS-13375)).

Because this work was meant to be a PoC and I am not sure by how far the gc issue is of practical importance, I opened this draft PR.

This PR

* adds a new submodule that provides a Cortex sink
* allows to configure Nephron's pipeline to output to Cortex
* allows to configure the pipeline to accumulate flow summaries in-depend of the use of Cortex. In that case other sinks also benefit from a reduced number of generated flow summaries
* extends the benchmark application to run Nephron's pipeline over different combinations of argument settings

2021-08-03 16:34 UTC, swachter commented
Implemented storage scheme as supposed in NMS-13374.

2021-08-12 19:38 UTC, j-white commented
Can we include the storage schema described in https://issues.opennms.org/browse/NMS-13374 as part of the README, or documentation in this project?

2021-08-13 10:48 UTC, swachter commented
I added a separate `persistence.md` document. I did not (yet) document the ES and Kafka output, though. Let me know if I should add sections for these, too.

2021-08-17 07:15 UTC, swachter commented on testing/src/test/java/org/opennms/nephron/testing/flowgen/CortexPaneIT.java
> +    private static class Wpc {
Changed to `Wpk`. (I guess it came from **c**ompoundKey, but **k**ey makes more sense.)

2021-08-17 07:24 UTC, swachter commented on main/src/main/java/org/opennms/nephron/CortexOptions.java
> +    void setCortexConsideredHosts(String value);
The filter is applied after "topK" calculation. Results stored in ES are not affected.

(In the meantime I found that there is an `IPAddressRange` class in OpenNMS. Maybe that should be used to filter hosts instead of a RegEx.)

2021-08-17 07:40 UTC, swachter commented on main/src/main/java/org/opennms/nephron/CortexOptions.java
> +    void setCortexHandleConversations(boolean value);
Ok. I removed the possibility to output conversations to Cortex.

2021-08-19 14:39 UTC, fooker commented on main/src/main/java/org/opennms/nephron/CortexOptions.java
> +    void setCortexConsideredHosts(String value);
> The filter is applied after "topK" calculation. Results stored in ES are not affected.

Makes sense. Follow up question: is this filter matching IPs only or does it match hostnames, too?
Maybe this needs some rewording: including into aggregations sounds like filter before aggregation. Maybe a native speaker could help out?

> (In the meantime I found that there is an IPAddressRange class in OpenNMS. Maybe that should be used to filter hosts instead of a RegEx.)

It would. 10.0.1.15 - 10.0.2.12 is super hard to express as an regex.

2021-08-20 09:15 UTC, swachter commented on main/src/main/java/org/opennms/nephron/CortexOptions.java
> +    void setCortexConsideredHosts(String value);
I switched to using the IPAddressRange machinery of OpenNMS. This now also supports CIDR notation.

The IPAddressRange machinery boils down to using `InetAddress.getByName(dottedNotation)`. Therefore, I think that host names can also be used when specifying the filter.

2021-08-21 14:05 UTC, fooker commented on main/src/main/java/org/opennms/nephron/CortexOptions.java
> +    void setCortexConsideredHosts(String value);
> The IPAddressRange machinery boils down to using InetAddress.getByName(dottedNotation). Therefore, I think that host names can also be used when specifying the filter.

Not exactly hat I was asking: If I specify a hostname in this parameter, will this hostname be used to match the hostnames that nephron is transporting besides the IPs of a flow?

Hostname resolution is something we should avoid (or at least not talk about) as it is done on the wrong system.

2021-08-25 12:03 UTC, swachter commented on main/src/main/java/org/opennms/nephron/CortexOptions.java
> +    void setCortexConsideredHosts(String value);
The filter checks the IP addresses of flows. Host names in the `cortexConsideredHosts` argument are resolved on the machine where Nephron is started. You are right, that might not always be what is expected. We can prohibit the use of host names if you prefer.

BTW: The flow classification engine that assigns applications to flows also supports host names in its rules. In that case host names are resolved where the classification engine runs. This may also be surprising.

2021-09-03 11:39 UTC, fooker requested changes

2021-09-03 11:39 UTC, fooker commented on cortex/src/test/java/org/opennms/nephron/cortex/CortexIoPipelineIT.java
> +//        });
Please remove

2021-09-03 11:39 UTC, fooker commented on cortex/src/test/java/org/opennms/nephron/cortex/CortexIoPipelineIT.java
> +        // `distinct` shoudl contain consecutive values for all seconds
```suggestion
        // `distinct` should contain consecutive values for all seconds
```

2021-09-03 11:39 UTC, fooker commented on main/src/main/java/org/opennms/nephron/CortexOptions.java
> +    @Description("Write URL for cortex (e.g. http://cortex:9009/api/v1/push).")
Add to desc: 'this also enables cortex persistence'

2021-09-06 11:08 UTC, swachter commented on cortex/src/main/java/org/opennms/nephron/cortex/PaneAccumulator.java
> +package org.opennms.nephron.cortex;
moved into util package in main module

2021-09-06 14:38 UTC, swachter commented on cortex/src/main/java/org/opennms/nephron/cortex/Heap.java
> +        private final Map<Instant, HeapValue<V>> values;
The expected Map size is small. At any moment there should be only a handful of windows for which currently a value gets accumulated for a specific key. In addition, Beam ships only a Coder for hash maps.
-> I would stay with using a map.

2021-09-06 15:04 UTC, swachter commented on cortex/src/main/java/org/opennms/nephron/cortex/Heap.java
> +                    .collect(Collectors.toList());
In general, the list of expired entries has size 1 because flushing is triggered base on processing when values are added to the heap. I added special treatment for size 1.

2021-09-06 15:38 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Pipeline.java
> +                .apply(paneAccumulator)
Moved to branch `jira/NMS-13467`

2021-09-07 07:22 UTC, fooker approved these changes
Please make sure that the generated code contains the license header, too.

2021-09-08 14:40 UTC, merged