NMS-13545: remove unnecessary fields from FlowSummary / FlowSummaryData
OpenNMS/nephron pull request #34
Opened 2021-09-01 18:23 UTC by swachter

Issue: https://issues.opennms.org/browse/NMS-13545

2021-09-13 19:42 UTC, fooker requested changes
A bunch of questions:

* This alters the output to elasticsearch, right?
* Do we have an feedback from customers if there is any use of this data beside the queries done by OpenNMS itself?
* Do we have a positive test run of the ONMS tests using the altered output format?

2021-09-13 19:42 UTC, fooker commented on main/src/main/java/org/opennms/nephron/CompoundKeyType.java
> -    private RefType[] parts;
unnecessary

2021-09-13 19:42 UTC, fooker commented on main/src/main/java/org/opennms/nephron/FlowSummaryData.java
> +        return key.equals(that.key) && aggregate.equals(that.aggregate);
This should use `Objects.equals` as there are no null-safety guarantees on the class.

2021-09-14 09:51 UTC, swachter commented on main/src/main/java/org/opennms/nephron/FlowSummaryData.java
> +        return key.equals(that.key) && aggregate.equals(that.aggregate);
Added non-null check in constructor.

2021-09-14 12:00 UTC, swachter commented
> A bunch of questions:
> 
>     * This alters the output to elasticsearch, right?

Right.

> 
>     * Do we have an feedback from customers if there is any use of this data beside the queries done by OpenNMS itself?

One customer is running this in production. How would the process be to get feedback from customers?

> 
>     * Do we have a positive test run of the ONMS tests using the altered output format?

The tests in OpenNMS still succeed.

2021-09-14 22:20 UTC, fooker commented
@swachter 

> > * Do we have an feedback from customers if there is any use of this data beside the queries done by OpenNMS itself?
> 
> One customer is running this in production. How would the process be to get feedback from other customers?

Not sure. Asking the support team, maybe?

> 
> > * Do we have a positive test run of the ONMS tests using the altered output format?
> 
> The tests in OpenNMS still succeed.

Is there a CI run for this that I haven't found? or was this just done by a local run?
Both is fine as long as it covered the smoke tests (if there is any regarding nephron).

2021-09-15 12:19 UTC, swachter commented
> @swachter
> 
> > > * Do we have an feedback from customers if there is any use of this data beside the queries done by OpenNMS itself?
> > 
> > 
> > One customer is running this in production. How would the process be to get feedback from other customers?
> 
> Not sure. Asking the support team, maybe?

Will do.

> 
> > > * Do we have a positive test run of the ONMS tests using the altered output format?
> > 
> > 
> > The tests in OpenNMS still succeed.
> 
> Is there a CI run for this that I haven't found? or was this just done by a local run?
> Both is fine as long as it covered the smoke tests (if there is any regarding nephron).

It was a local run. There are no smoke tests for Nephron. All Nephron related tests are under `features/flows/itests`

2021-09-15 13:22 UTC, fooker requested changes
Still has some unnecessary changes. beside that, this is good to merge.

2021-09-16 08:42 UTC, swachter commented
Support did not raise objections to dropping these fields.

2021-09-16 08:43 UTC, merged