Extend nephron options
OpenNMS/nephron pull request #5
Opened 2020-10-26 23:22 UTC by Naicisum

Extend Nephron options to include additional Elasticsearch socket/connect timeout parameters and utilize Elasticsearch retry count and duration options.

2020-11-04 13:18 UTC, fooker requested changes
Looks god from technical perspective. Only minor code quality improvements.

2020-11-04 13:18 UTC, fooker commented on main/src/main/java/org/opennms/nephron/Pipeline.java
> +        private long elasticRetryDuration;
Please, make these variables `final`, add constructor parameters and assign them in constructor. By doing so, we ensure they have well defined values (using `0` for `retryCount` seems to be wrong)

2020-11-04 13:18 UTC, fooker commented on main/src/main/java/org/opennms/nephron/Pipeline.java
> +            this.elasticRetryDuration = options.getElasticRetryDuration();
Instead of assigning here, pass to forwarding constructor call.

2020-11-04 18:15 UTC, Naicisum commented on main/src/main/java/org/opennms/nephron/Pipeline.java
> +        private long elasticRetryDuration;
We can't use `final` here as I need access to the NephronOptions object which is only available in the public function below. This is necessary due to the scope as these values are needed inside the `expand` function which does not have access to a NephronOptions.

If you have a better way. I am all ears

2020-11-04 18:15 UTC, Naicisum commented on main/src/main/java/org/opennms/nephron/Pipeline.java
> +            this.elasticRetryDuration = options.getElasticRetryDuration();
Sure, I can move these assignments to the function above and pass them.

2020-11-05 09:31 UTC, fooker approved these changes

2020-11-05 09:31 UTC, fooker commented on main/src/main/java/org/opennms/nephron/Pipeline.java
> +        private long elasticRetryDuration;
With your latest changes, this should just work. There is only one write to the variables left (the one in the constructor) which is fin to make them `final`. But your latest changes are just fine.

2020-11-05 14:21 UTC, merged