NMS-12967: Fix exploding flow into buckets
OpenNMS/nephron pull request #7
Opened 2020-11-05 14:17 UTC by fooker

Duplicating the flow to be associated with all relevant buckets needs to cover the full range. This fix ensures that a flow spanning [5s, 23s] is now marked with timestamps {5, 15, 25} and therefore is associated to the buckets { [0, 10), [10, 20), [20, 30) } (with window-size of 10).

2020-11-05 14:45 UTC, j-white commented on main/src/test/java/org/opennms/nephron/FlowAnalyzerTest.java
> +                .withFlow(Instant.ofEpochSecond(17), Instant.ofEpochSecond(32),
If I change the start of the flow from 17 to 10, I would expect the same results, but the assertions fail with a flow in "Bucket 4".

2020-11-05 14:45 UTC, j-white commented
Nice find

2020-11-05 14:49 UTC, fooker commented on main/src/test/java/org/opennms/nephron/FlowAnalyzerTest.java
> +                .withFlow(Instant.ofEpochSecond(17), Instant.ofEpochSecond(32),
Damn, I somehow know. The chance of hitting this is 1 to 60000 on a 1 minute window size...
Will fix.

2020-11-05 21:03 UTC, fooker commented on main/src/test/java/org/opennms/nephron/FlowAnalyzerTest.java
> +                .withFlow(Instant.ofEpochSecond(17), Instant.ofEpochSecond(32),
Fixed the formula and added some more tests.

2020-11-10 10:03 UTC, fooker commented
I've added a test to ensure that flows no covering more than a bucket are handled correct, too.
This also includes checking the calculated bytes per bucket.

2020-11-20 01:21 UTC, Naicisum commented on main/src/main/java/org/opennms/nephron/MyCustomTimestampPolicyWithLimitedDelay.java
> +        System.out.printf("MOO: System clock at: %s, watermark at: %s num messages in backlog: %d\n", Instant.now(), wm, ctx.getMessageBacklog());
Can we convert this to a rate limited event or a metric?

2020-12-21 15:22 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Pipeline.java
> +            return Instant.ofEpochMilli(doc.getFirstSwitched().getValue());
Maybe `deltaSwitched` should be used here.  `deltaSwitched` is also used when determining the collection of windows a flow document belongs to.

2020-12-21 15:22 UTC, swachter commented on main/src/main/java/org/opennms/nephron/FlowWindows.java
> +    public static class FlowWindow extends BoundedWindow {
AFAIS `nodeId` is not used anywhere. A standard `IntervalWindow` may be used.

2020-12-21 15:22 UTC, swachter commented on main/src/main/java/org/opennms/nephron/FlowWindows.java
> +        }
This algorithms looks complicated to me. Maybe the following algorithm would be easier to understand:

```
        long firstWindow = flow.getDeltaSwitched().getValue() / windowSize; // the first window the flow falls into
        long lastWindow = flow.getLastSwitched().getValue() / windowSize; // the last window the flow falls into (assuming lastSwitched is inclusive)

        final List<FlowWindow> windows = Lists.newArrayList();
        for (long w = firstWindow; w <= lastWindow; w++) {
            Instant start = new Instant(w * windowSize);
            windows.add(new FlowWindow(start, start.plus(this.size), c.element().getExporterNode().getNodeId()));
        }
```

2020-12-21 22:58 UTC, Naicisum commented on main/src/main/java/org/opennms/nephron/FlowWindows.java
> +        }
The issue I see with `w++` is that it is not necessarily the `windowSize`

2020-12-22 07:32 UTC, swachter commented on main/src/main/java/org/opennms/nephron/FlowWindows.java
> +        }
I do not understand. The window start and end is calculated as multiples of `w`: `Instant start = new Instant(w * windowSize);`

2020-12-22 07:40 UTC, Naicisum commented on main/src/main/java/org/opennms/nephron/FlowWindows.java
> +        }
Your suggested `for` loop increments based on `w++` and not `w += windowSize` as is done in the `while` loop above.

2020-12-22 08:34 UTC, swachter commented on main/src/main/java/org/opennms/nephron/FlowWindows.java
> +        }
`w` is a window number and not some time in milliseconds. It is simple a counter starting at the first window number the flows falls into and ending at the last window number.

The current implementation generates windows that start at multiples of the windows size. This is enforced by the line:

```
final Instant start = new Instant(timestamp - (timestamp % this.size.getMillis()));
```
The same is true for the proposed new implemeentation.

2021-01-20 10:22 UTC, fooker commented on main/src/main/java/org/opennms/nephron/MyCustomTimestampPolicyWithLimitedDelay.java
> +        System.out.printf("MOO: System clock at: %s, watermark at: %s num messages in backlog: %d\n", Instant.now(), wm, ctx.getMessageBacklog());
It was there for debugging only. Removed it completely.

2021-01-20 11:23 UTC, fooker commented on main/src/main/java/org/opennms/nephron/FlowWindows.java
> +    public static class FlowWindow extends BoundedWindow {
It is used in the `equals` and `hashCode` implementations. That's the reason why it was added.

2021-01-20 11:26 UTC, fooker commented on main/src/main/java/org/opennms/nephron/Pipeline.java
> +            return Instant.ofEpochMilli(doc.getFirstSwitched().getValue());
The timestamp is used to calculate the watermark and therefore used to close down the windows. Using a "lower" value would mean, that windows will be closed only if flows arrive that's start(delta) time would be after the previous flows end time.

2021-01-20 11:29 UTC, fooker commented on main/src/main/java/org/opennms/nephron/FlowWindows.java
> +        }
The main difference is that with the current implementation, window boundaries will not be aligned to bucket boundaries. Assuming window size of 10s, considering a flow with a start time of 5s will create a window from 5s to 15s, not 0s to 10s. I'm nut sure if this makes a difference at all. But this sounds like something that I would test before pushing it in this PR.

2021-01-20 20:27 UTC, Naicisum commented on main/src/main/java/org/opennms/nephron/FlowWindows.java
> +        }
Ideally, the boundaries need to fall on real world boundaries, not flow boundaries. 0s should be 11:00:00, 06:01:00, or 23:43:00. The same for 10s, 15s, 5m, 1h, etc...

2021-01-22 23:39 UTC, fooker commented
I've merged master, fixed the review comments and integrated the tests we've build lately. There are no major changes to the main code since last review but only changes to tests.

2021-01-25 08:44 UTC, swachter commented on main/src/main/java/org/opennms/nephron/FlowWindows.java
> +        private final Instant end;
As far as I understand the code `start` is inclusive and `end` exclusive. This should be documented.

If `end` is exclusive then the check in `KeyFlowBy.aggregatize`:

```
                    flow.getLastSwitched().getValue() <= window.end().getMillis())
```

is wrong.

2021-01-25 08:55 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Groupings.java
> +        private Optional<Aggregate> aggregatize(final FlowWindows.FlowWindow window, final FlowDocument flow, final String hostname) {
The `flow.getLastSwitched().getValue() <= window.end().getMillis())` test below (on line 153) should be changed into `flow.getLastSwitched().getValue() < window.end().getMillis())`.

2021-01-25 09:33 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Groupings.java
>              long flowDurationMs = flow.getLastSwitched().getValue() - flow.getDeltaSwitched().getValue();
The calculation does not carefully handle inclusive / exclusive bounds. `flow.lastSwitched` is inclusive whereas `window.end` is exclusive. The multiplier calculation should be changed to:

```
            // The flow duration ranges [delta_switched, last_switched] (both bounds are inclusive)
            long flowDurationMs = flow.getLastSwitched().getValue() - flow.getDeltaSwitched().getValue() + 1;
            if (flowDurationMs <= 0) {
                // Non-positive duration, pass
                LOG.warn("Ignoring flow with non-positive duration: {}. Flow: {}", flowDurationMs, flow);
                return Optional.empty();
            }

            final double multiplier;
            if (flowDurationMs == 1) {
                // Double check that the flow is in fact in this window
                if (flow.getDeltaSwitched().getValue() >= window.start().getMillis()
                    && flow.getLastSwitched().getValue() < window.end().getMillis()) {
                    // Use the entirety of the flow bytes
                    multiplier = 1.0;
                } else {
                    return Optional.empty();
                }

            } else {
                // Now determine how many milliseconds the flow overlaps with the window bounds
                long flowWindowOverlapMs =
                        // flow.lastSwitched is inclusive, window.end is exclusive
                        // -> calculate the inclusive upper bound of the overlap
                        // -> subtract 1 from window.end for a corresponding inclusive window upper bound
                        Math.min(flow.getLastSwitched().getValue(), window.end().getMillis() - 1)
                        // subtract the inclusive lower bound of the overlap
                        - Math.max(flow.getDeltaSwitched().getValue(), window.start().getMillis())
                        // add one to the difference because the upper bound is inclusive
                        + 1;
                if (flowWindowOverlapMs <= 0) {
                    // Flow should not be in this windows! pass
                    return Optional.empty();
                }

                // Output value proportional to the overlap with the window
                multiplier = flowWindowOverlapMs / (double) flowDurationMs;
            }
```

2021-01-25 09:42 UTC, swachter commented on main/src/main/java/org/opennms/nephron/FlowWindows.java
> +        }
> The main difference is that with the current implementation, window boundaries will not be aligned to bucket boundaries. Assuming window size of 10s, considering a flow with a start time of 5s will create a window from 5s to 15s, not 0s to 10s. I'm nut sure if this makes a difference at all. But this sounds like something that I would test before pushing it in this PR.

I don't think so. The current implementation determines the window start by calculating:

```
final Instant start = new Instant(timestamp - (timestamp % this.size.getMillis()));
```

The modulo calculation results in windows start times that are multiples of the window size.

2021-01-25 09:49 UTC, swachter commented on main/src/main/java/org/opennms/nephron/FlowWindows.java
> + * end (inclusive) while keeping the flow unchanged.
Calculations become easier if upper bounds are considered exclusive. The instantiation of `FlowWindow` in the method `assignWindows()` indicates that `end` is considered `exclusive`:

```
new FlowWindow(start, start.plus(this.size), ...)
```

If `end` would be inclusive then boundaries would belong both to the previous and the following window.

2021-01-25 10:02 UTC, swachter commented on main/src/main/java/org/opennms/nephron/FlowWindows.java
> +            windows.add(new FlowWindow(start, start.plus(this.size), c.element().getExporterNode().getNodeId()));
`window.end` is `inclusive` therefore the end must be calculated by `start.plus(this.size - 1)`.

2021-01-25 10:43 UTC, fooker commented on main/src/main/java/org/opennms/nephron/FlowWindows.java
> +        private final Instant end;
This is shameless stolen from `IntervalWindow` which was used before. Therefore I added some comments and made `maxTimestamp` inclusive.

2021-01-25 10:47 UTC, fooker commented on main/src/main/java/org/opennms/nephron/FlowWindows.java
> +            windows.add(new FlowWindow(start, start.plus(this.size), c.element().getExporterNode().getNodeId()));
I would consider the window end to be exclusive. This makes all calculation way more easy. This seems to be the default behavior as it was already implemented by `IntervalWindow` before.

2021-01-25 10:55 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Groupings.java
> +            // window bound a little bit but makes sums correct.
Can you elaborate why this calculation makes sums correct? IMO the precision of rounding is presumably better than just truncating but correctness of sums is not guaranteed.

The correctness of the sum could be achieved by changing the calculation logic the following way:
* view the traffic contributed by a flow as a line in a coordinate system with the x-axis corresponding to millis and y-axis corresponds to the number of bytes. The line starts at (`deltaSwitched`, 0) and ends at (`lastSwitched`, totalNumberOfBytes)`
* to calculate the number of bytes in a window subtract the `y` value at the end of this window from the `y` values at the end of the previous window.
* This calculation method ensures that rounding errors are levelled out over the whole set of windows.

2021-01-25 10:56 UTC, fooker commented on main/src/main/java/org/opennms/nephron/Groupings.java
>              long flowDurationMs = flow.getLastSwitched().getValue() - flow.getDeltaSwitched().getValue();
Assuming that both flow and window ends are exclusive, the original algorithm seems to be correct.

This version would drop flows where `lasSwitched - deltaSwitched == 0`, but analyzing existing data shows that this happens a lot and contains a considerable amount of data. Therefore, even if not technically correct, I would assume the timestamps to be end-exclusive for these calculations (assuming sub-millisecond resolution is rounded down).

2021-01-25 11:08 UTC, swachter commented on main/src/main/java/org/opennms/nephron/NephronOptions.java
> +    @Description("Amount of time to wait before firing the pane for early updates." +
Early results are in conflict with the possible change to 'discardingAccumulation` aggregation mode. Why do we need it. Do you foresee that the `maxDelay` is a large amount of time and you therefore want to have preliminary results?

2021-01-25 11:12 UTC, swachter commented on main/src/main/java/org/opennms/nephron/MyCustomTimestampPolicyWithLimitedDelay.java
> +public class MyCustomTimestampPolicyWithLimitedDelay<K, V> extends TimestampPolicy<K, V> {
Maybe the `MyCustom` prefix can be dropped from the class name. A more descriptive name would be `TimstampPolicyWithDelayedWatermark`.

2021-01-25 11:17 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Pipeline.java
> +        AfterWatermark.AfterWatermarkEarlyAndLate trigger = AfterWatermark
Not sure, if we should have early firings (because of possible `discardingAccumulation` aggregation mode).

2021-01-25 11:20 UTC, fooker commented on main/src/main/java/org/opennms/nephron/Groupings.java
> +            // window bound a little bit but makes sums correct.
True, maybe changing the comment from "correct" to "more correct"?

I'm open for proposals on how to do that while only having knowledge about a single window.

2021-01-25 11:25 UTC, fooker commented on main/src/main/java/org/opennms/nephron/NephronOptions.java
> +    @Description("Amount of time to wait before firing the pane for early updates." +
AFAIR this was a requirement from a customer. It does not only help to see results with a large `maxDelay` but also with larger window size. But the main reason for this to add is to see results from exporters which have their clock misconfigured to return a future time.

2021-01-25 11:36 UTC, fooker commented on main/src/main/java/org/opennms/nephron/FlowWindows.java
> +        }
I've adopted to the algorithm proposed above.

2021-01-25 11:41 UTC, fooker commented on main/src/main/java/org/opennms/nephron/Pipeline.java
> +        AfterWatermark.AfterWatermarkEarlyAndLate trigger = AfterWatermark
I'm not totally sold to the idea of `discardingAccumulation` yet. This needs some further discussion and should not be part of this topic. Even so, I don't think that we should block a requested feature for a maybe-possible optimization. If the proposed optimization should really happen, it must have this feature, too (or provide another workaround for it).

2021-01-25 11:56 UTC, fooker commented on main/src/main/java/org/opennms/nephron/MyCustomTimestampPolicyWithLimitedDelay.java
> +public class MyCustomTimestampPolicyWithLimitedDelay<K, V> extends TimestampPolicy<K, V> {
I'Ve renamed it to `FlowTimestampPolicy` and also removed the `timestampFunction` using the `ReadFromKafka.getTimestamp` function directly.

2021-01-25 12:31 UTC, swachter requested changes

2021-01-25 12:31 UTC, swachter commented on main/src/test/java/org/opennms/nephron/FlowAnalyzerIT.java
> +        Thread.sleep(10_000);
Why do we need to wait for the Kafka consumer? Production and consumption should be decoupled. Later on we wait for the results appearing in Elastic anyway.

2021-01-25 12:42 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Groupings.java
>              long flowDurationMs = flow.getLastSwitched().getValue() - flow.getDeltaSwitched().getValue();
> Assuming that both flow and window ends are exclusive, the original algorithm seems to be correct.

I also prefer upper bounds to be exclusive. However, in the current implementation `FlowWindow.maxTimestamp()` returns `end`. Therefore `end` must be interpreted as inclusive. Copied from `BoundedWindow.java`:

```
  /** Returns the inclusive upper bound of timestamps for values in this window. */
  public abstract Instant maxTimestamp();
```

> 
> This version would drop flows where `lasSwitched - deltaSwitched == 0`, but analyzing existing data shows that this happens a lot and contains a considerable amount of data. Therefore, even if not technically correct, I would assume the timestamps to be end-exclusive for these calculations (assuming sub-millisecond resolution is rounded down).

My proposal calculates `flowDurationMs` the following way (note the `+1` at the end):

```
long flowDurationMs = flow.getLastSwitched().getValue() - flow.getDeltaSwitched().getValue() + 1;
```

Therefore flows with `lastSwitched == deltaSwitched` would not get dropped.

2021-01-25 12:44 UTC, swachter commented on main/src/main/java/org/opennms/nephron/FlowWindows.java
> +            windows.add(new FlowWindow(start, start.plus(this.size), c.element().getExporterNode().getNodeId()));
Unfortunately, `window.end` must be interpreted as inclusive - at least as long as we return that value for `maxTimestamp`.

2021-01-25 12:46 UTC, fooker commented on main/src/main/java/org/opennms/nephron/Groupings.java
>              long flowDurationMs = flow.getLastSwitched().getValue() - flow.getDeltaSwitched().getValue();
I've already changed `FlowWindow.maxTimestamp` to be inclusive while `FlowWindow.end` being exclusive. I would like to keep this similar to the original `IntervalWindow` code.

2021-01-25 12:48 UTC, fooker commented on main/src/main/java/org/opennms/nephron/Groupings.java
>              long flowDurationMs = flow.getLastSwitched().getValue() - flow.getDeltaSwitched().getValue();
To make this more clear: I think assuming that `lastSwitched` is inclusive is/was a misinterpretation. I've updated to comments and math accordingly. So everything can stay [inclusive, exclusive) and may can be clean and simple.

2021-01-25 12:52 UTC, fooker commented on main/src/main/java/org/opennms/nephron/FlowWindows.java
> +            windows.add(new FlowWindow(start, start.plus(this.size), c.element().getExporterNode().getNodeId()));
Returning `end.minus(1)` in `maxTimestamp` solves this.

2021-01-25 13:14 UTC, fooker commented on main/src/test/java/org/opennms/nephron/FlowAnalyzerIT.java
> +        Thread.sleep(10_000);
The nephron kafka consumer drops messages produced before the consumer was started (which is by intention).

2021-01-25 14:12 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Groupings.java
> +            // window bound a little bit but makes sums correct.
The calculation can be done for each single window separately. The gist of the code below is that the calculation for `bytesAtPreviousEnd` returns exactly the same result as `bytesAtEnd` for the previous window. This should work:

```
        private Optional<Aggregate> aggregatize(final FlowWindows.FlowWindow window, final FlowDocument flow, final String hostname) {
            // The flow duration ranges [delta_switched, last_switched] (both bounds are inclusive)
            long deltaSwitched = flow.getDeltaSwitched().getValue();
            long lastSwitched = flow.getLastSwitched().getValue();
            long flowDurationMs = lastSwitched - deltaSwitched + 1;
            if (flowDurationMs <= 0) {
                // Non-positive duration, pass
                LOG.warn("Ignoring flow with non-positive duration: {}. Flow: {}", flowDurationMs, flow);
                return Optional.empty();
            }

            // the start (inclusive) of the flow in this window
            long overlapStart = Math.max(deltaSwitched, window.start().getMillis());
            // the end (inclusive) of the flow in this window
            long overlapEnd = Math.min(lastSwitched, window.end().getMillis());

            long previousEnd = overlapStart - 1;

            double multiplier = 1.0;
            if (flow.hasSamplingInterval()) {
                double samplingInterval = flow.getSamplingInterval().getValue();
                if (samplingInterval > 0) {
                    multiplier = samplingInterval;
                }
            }

            long numBytes = flow.getNumBytes().getValue();
            long bytesAtPreviousEnd = (long)((previousEnd - deltaSwitched + 1) * numBytes * multiplier / flowDurationMs);
            long bytesAtEnd = (long)((overlapEnd - deltaSwitched + 1) * numBytes * multiplier / flowDurationMs);

            long bytes = bytesAtEnd - bytesAtPreviousEnd;

            // Track
            flowsInWindow.inc();

            final long bytesIn;
            final long bytesOut;
            if (Direction.INGRESS.equals(flow.getDirection())) {
                bytesIn = bytes;
                bytesOut = 0;
            } else {
                bytesIn = 0;
                bytesOut = bytes;
            }

            return Optional.of(new Aggregate(bytesIn, bytesOut, hostname));
        }
```

I verified some cases by pencil. This would be a great candidate for property based testing, though.

2021-01-25 14:57 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Groupings.java
>              long flowDurationMs = flow.getLastSwitched().getValue() - flow.getDeltaSwitched().getValue();
> To make this more clear: I think assuming that `lastSwitched` is inclusive is/was a misinterpretation. I've updated to comments and math accordingly. So everything can stay [inclusive, exclusive) and may can be clean and simple.

I checked the raw flows that I collected locally. For all of these flows it seems that `deltaSwitched == lastSwitched`. I think you came to the same conclusion that this is a common case in your comment above. Therefore it seems more reasonable to me to interpret `lastSwitched` to be **inclusive**.

2021-01-25 15:26 UTC, swachter commented on main/src/main/java/org/opennms/nephron/FlowWindows.java
> +        long lastWindow = flow.getLastSwitched().getValue() / windowSize; // exclusive
If `lastSwitched` is considered exclusive then this calculation has to consider the corner case where `lastSwitched` falls onto a window start. I think `lastSwitched` should be considered inclusive. Then this line of code may stay, but the comment must be updated.

2021-01-25 17:22 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Groupings.java
>              long flowDurationMs = flow.getLastSwitched().getValue() - flow.getDeltaSwitched().getValue();
In some sense the question how to interpret `lastSwitched` boils down to the question what "duration" we assume for a flow with `deltaSwitched = lastSwitched`. Both, `0` or `1` seem natural choices. However, when the relative contribution of a flow is calculated, the more general formula calculates the "contribution factor" by diving the duration of the overlap of a flow with window by the total duration of a flow. In case the flow duration may be `0` special handling for that case is required (because 0/0 is not 1).

2021-01-25 22:14 UTC, fooker commented on main/src/main/java/org/opennms/nephron/Groupings.java
>              long flowDurationMs = flow.getLastSwitched().getValue() - flow.getDeltaSwitched().getValue();
Current implementation just assumes that sub-millisecond event time is just rounded down. A flow having a duration of `0` just means that the flow took less than a millisecond to happen.

I think the most relevant point here is to not change the behavior. Because if we do this, this means that we should change the calculation for raw flows, too.

TBH, this does not really change anything. Even if there is/was a flow assigned to a single millisecond of wrong window, this will barely change any numbers. Even on a fully utilized link and a window size of 1 second this would shift the results by 1/1000 of the real value. So, If you think the calculations are wrong (in general) pleas go ahead and open an issue for that.

2021-01-26 07:51 UTC, swachter commented on main/src/main/java/org/opennms/nephron/FlowWindows.java
> +        long lastWindow = flow.getLastSwitched().getValue() / windowSize; // exclusive
If you stick with `lastSwitched` being exclusive then the calculation for the last windows must be changed to:

```
long lastWindow = (flow.getLastSwitched().getValue() - 1)/ windowSize; // exclusive
```

2021-01-26 10:01 UTC, fooker commented on main/src/main/java/org/opennms/nephron/FlowWindows.java
> +        long lastWindow = flow.getLastSwitched().getValue() / windowSize; // exclusive
Just assume that `lastWindow` is inclusive. Than the math is correct and the loop works out, too. I've removed/updated the comment.

2021-01-26 12:46 UTC, fooker commented on main/src/main/java/org/opennms/nephron/Groupings.java
>              long flowDurationMs = flow.getLastSwitched().getValue() - flow.getDeltaSwitched().getValue();
After some more discussion, the current solution is considered correct.

2021-01-26 14:46 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Groupings.java
>              long flowDurationMs = flow.getLastSwitched().getValue() - flow.getDeltaSwitched().getValue();
We agreed in another review conversation that `flow.lastSwitched` shall be considered **inclusive**. The distribution of flows into their windows is done accordingly. The `aggregatize` method here interprets `flow.lastSwitched` as being **exclusive**. `aggregatize` returns the correct result in the sense that the "sums" are preserved. I would appreciate if the alternative calculation given in the conversation below would be used, though.

2021-01-26 15:06 UTC, fooker commented on main/src/main/java/org/opennms/nephron/Groupings.java
>              long flowDurationMs = flow.getLastSwitched().getValue() - flow.getDeltaSwitched().getValue();
True, resolved the wrong conversation.

2021-01-28 17:59 UTC, mszoek commented on main/src/main/java/org/opennms/nephron/Groupings.java
> +            // window bound a little bit but makes sums correct.
What kind of performance impact would you expect from calculating the window end this way?

2021-01-29 08:39 UTC, swachter commented on main/src/main/java/org/opennms/nephron/Groupings.java
> +            // window bound a little bit but makes sums correct.
I do not expect a measurable performance impact. The new algorithm has less branching logic but may have more arithmetic operations.

We decided to move the change of the `agregatize` method into another PR.

2021-01-29 08:51 UTC, swachter approved these changes
LGTM

2021-01-29 12:57 UTC, merged